
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'7\x03\x1d\xbe\xe5\xedx+\xa9\xb6-:T\xf9T\xf3'
    
_lr_action_items = {'RANGE':([59,],[63,]),'INTEGER':([32,],[47,]),'LESS':([68,],[73,]),'KEY':([31,],[46,]),'WHERE':([61,62,],[65,66,]),'RESET':([0,],[4,]),'PRIMARY':([17,],[31,]),'$end':([1,2,3,5,7,9,11,12,14,15,16,19,21,22,23,25,26,38,39,42,43,44,45,51,52,53,54,55,56,57,58,59,61,62,64,69,70,71,75,76,77,],[-8,-3,-7,-10,-6,0,-9,-13,-14,-2,-12,-5,-4,-11,-1,-15,-23,-16,-17,-18,-31,-27,-30,-26,-25,-32,-33,-24,-29,-28,-22,-21,-37,-36,-19,-35,-34,-20,-39,-40,-38,]),'DATABASE':([4,],[25,]),'FROM':([33,34,],[49,50,]),'ALL':([18,],[33,]),'UPDATE':([0,],[6,]),'CREATE':([0,],[8,]),'GREATER':([68,],[72,]),'DEFINE':([0,],[10,]),'RELATION':([4,10,20,24,],[26,29,36,39,]),'INSERT':([0,],[13,]),'EXIT':([0,],[14,]),'WORD':([6,13,18,20,28,29,30,35,36,40,41,43,45,46,47,49,50,60,65,66,],[27,30,34,37,41,42,45,51,52,45,55,45,45,58,59,61,62,64,68,68,]),'NUMBER':([27,30,37,40,43,45,48,63,67,72,73,74,],[40,43,53,43,43,43,60,67,71,75,76,77,]),'SET':([0,],[17,]),'SELECT':([0,],[18,]),'DELETE':([0,],[20,]),'EQUAL':([68,],[74,]),'GET':([0,],[24,]),'ATTRIBUTE':([17,],[32,]),'CHARACTER':([32,],[48,]),'TABLE':([8,20,24,],[28,35,38,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'get_cmd':([0,],[1,]),'set_cmd':([0,],[15,]),'reset_cmd':([0,],[16,]),'create_cmd':([0,],[2,]),'select_cmd':([0,],[3,]),'delete_cmd':([0,],[19,]),'delete_relation_cmd':([0,],[5,]),'update_cmd':([0,],[7,]),'insert_cmd':([0,],[21,]),'command':([0,],[9,]),'expr':([65,66,],[69,70,]),'attribute_expr':([30,40,43,45,],[44,54,56,57,]),'exit_cmd':([0,],[22,]),'define_cmd':([0,],[23,]),'reset_relation_cmd':([0,],[12,]),'delete_table_cmd':([0,],[11,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> command","S'",1,None,None,None),
  ('command -> define_cmd','command',1,'p_command','SqlYacc.py',48),
  ('command -> set_cmd','command',1,'p_command','SqlYacc.py',49),
  ('command -> create_cmd','command',1,'p_command','SqlYacc.py',50),
  ('command -> insert_cmd','command',1,'p_command','SqlYacc.py',51),
  ('command -> delete_cmd','command',1,'p_command','SqlYacc.py',52),
  ('command -> update_cmd','command',1,'p_command','SqlYacc.py',53),
  ('command -> select_cmd','command',1,'p_command','SqlYacc.py',54),
  ('command -> get_cmd','command',1,'p_command','SqlYacc.py',55),
  ('command -> delete_table_cmd','command',1,'p_command','SqlYacc.py',56),
  ('command -> delete_relation_cmd','command',1,'p_command','SqlYacc.py',57),
  ('command -> exit_cmd','command',1,'p_command','SqlYacc.py',58),
  ('command -> reset_cmd','command',1,'p_command','SqlYacc.py',59),
  ('command -> reset_relation_cmd','command',1,'p_command','SqlYacc.py',60),
  ('exit_cmd -> EXIT','exit_cmd',1,'p_exit_cmd','SqlYacc.py',64),
  ('reset_cmd -> RESET DATABASE','reset_cmd',2,'p_reset_cmd','SqlYacc.py',70),
  ('get_cmd -> GET TABLE','get_cmd',2,'p_get_cmd','SqlYacc.py',85),
  ('get_cmd -> GET RELATION','get_cmd',2,'p_get_cmd','SqlYacc.py',86),
  ('define_cmd -> DEFINE RELATION WORD','define_cmd',3,'p_define_cmd','SqlYacc.py',107),
  ('set_cmd -> SET ATTRIBUTE CHARACTER NUMBER WORD','set_cmd',5,'p_set_cmd','SqlYacc.py',129),
  ('set_cmd -> SET ATTRIBUTE INTEGER WORD RANGE NUMBER NUMBER','set_cmd',7,'p_set_cmd','SqlYacc.py',130),
  ('set_cmd -> SET ATTRIBUTE INTEGER WORD','set_cmd',4,'p_set_cmd','SqlYacc.py',131),
  ('set_cmd -> SET PRIMARY KEY WORD','set_cmd',4,'p_set_cmd','SqlYacc.py',132),
  ('reset_relation_cmd -> RESET RELATION','reset_relation_cmd',2,'p_reset_relation_cmd','SqlYacc.py',172),
  ('create_cmd -> CREATE TABLE WORD WORD','create_cmd',4,'p_create_cmd','SqlYacc.py',179),
  ('delete_relation_cmd -> DELETE RELATION WORD','delete_relation_cmd',3,'p_delete_relation_cmd','SqlYacc.py',210),
  ('delete_table_cmd -> DELETE TABLE WORD','delete_table_cmd',3,'p_delete_table_cmd','SqlYacc.py',231),
  ('insert_cmd -> INSERT WORD attribute_expr','insert_cmd',3,'p_insert_cmd','SqlYacc.py',251),
  ('attribute_expr -> WORD attribute_expr','attribute_expr',2,'p_attribute_expr','SqlYacc.py',280),
  ('attribute_expr -> NUMBER attribute_expr','attribute_expr',2,'p_attribute_expr','SqlYacc.py',281),
  ('attribute_expr -> WORD','attribute_expr',1,'p_attribute_expr','SqlYacc.py',282),
  ('attribute_expr -> NUMBER','attribute_expr',1,'p_attribute_expr','SqlYacc.py',283),
  ('delete_cmd -> DELETE WORD NUMBER','delete_cmd',3,'p_delete_cmd','SqlYacc.py',291),
  ('update_cmd -> UPDATE WORD NUMBER attribute_expr','update_cmd',4,'p_update_cmd','SqlYacc.py',310),
  ('select_cmd -> SELECT WORD FROM WORD WHERE expr','select_cmd',6,'p_select_cmd','SqlYacc.py',330),
  ('select_cmd -> SELECT ALL FROM WORD WHERE expr','select_cmd',6,'p_select_cmd','SqlYacc.py',331),
  ('select_cmd -> SELECT WORD FROM WORD','select_cmd',4,'p_select_cmd','SqlYacc.py',332),
  ('select_cmd -> SELECT ALL FROM WORD','select_cmd',4,'p_select_cmd','SqlYacc.py',333),
  ('expr -> WORD EQUAL NUMBER','expr',3,'p_expr','SqlYacc.py',409),
  ('expr -> WORD GREATER NUMBER','expr',3,'p_expr','SqlYacc.py',410),
  ('expr -> WORD LESS NUMBER','expr',3,'p_expr','SqlYacc.py',411),
]
